### ISSUE TITLE
Create mappings for Sakuli Metrics to prometheus metrics representation

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli-enterprise-forwarder#16]
Story: https://github.com/sakuli/sakuli-enterprise-forwarder/issues/14

Acc. Crit.:
- Test suites are mapped
- Test cases are mapped 
- Test steps are mapped
  - Step duration is mapped
  - Step threshold information is mapped (okay, warning, critical)
- ~screeshots are mapped~
- mapping is documented

**Comment by tnobody** [comment]
After some research we found out that prometheus is not intended to collect other data than pure metrics (floats). Therefore we removed the mapped screenshots from the acct. Crit
