### ISSUE TITLE
Identify required push gateway config

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli-enterprise-forwarder#17]
Story: https://github.com/sakuli/sakuli-enterprise-forwarder/issues/14

Acc. Crit:
- Push gateway configuration parameter for the sakuli forwarder are identified
- property names have been specified

**Comment by s1hofmann** [comment]
Just a thought from my side: Should we have a look at [textfile exporters](https://github.com/prometheus/node_exporter#textfile-collector) as well?
