### ISSUE TITLE
configurable prefix 

### ISSUE THREAD

**Issue by ZNicoZ** [sakuli/sakuli-enterprise-forwarder#24]
As a sakuli monitoring user, I want the prefix of a monitoring input being configurable.

Note from a DEV:
```
Anpassbar könnte man das machen, das kommt aus dem Forwarder: (caseIdx: string) => 's_${caseIdx}_${testStepIdx}_${testStep.id}=${getOutputDuration(testStep)};'
```

Acc.Crit.:
- [ ] caseIdx, testStepIdx and testStep.id are configurable with eg. properties

**Comment by svettwer** [comment]
Why would you want to change this @ZNicoZ?

**Comment by svettwer** [comment]
Closed due: No clue anymore
