### ISSUE TITLE
Add website URL to spool files

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli-enterprise-forwarder#30]
As a Sakuli with checkmk user, I want Sakuli to add the url of the tested website to the spool files, so that it can be linked in the checkmk frontend.

**Additional information**
WWI Requirement - Check if the URL transportation in spool files is a general feature or something special for WWI.

[sample spool files](https://github.com/sakuli/sakuli-enterprise-forwarder/files/4184611/Sakuli_1_spool.zip)

**Acceptance criteria**
- [x] Configuration URL transport on/off
- [x] Configuration about what to be transported: testsuite.property -> e.g. `sakuli.forwarder.check_mk.url=url`
- [x] Link is parsed and shown as an world Icon in checkmk when configurated

**Comment by ZNicoZ** [comment]
I´ll speak to comNet today and will ask them if they have knowledge about this requirement with their customers.

**Comment by ZNicoZ** [comment]
Feedback comNet:

Parsing der URL kann in CheckMK aktiviert bzw. deaktiviert werden. Default waren sie sich nicht sicher, denken aber, dass per default das Parsing deaktiviert ist.

Für uns heißt das aus meiner Sicht:
- Kein WWI spezifisches Feature
- Konfigurationsschalter, der die Übergabe der URL aktiviert/deaktiviert
- Konfiguration was / welche URL übergeben wird

**Comment by svettwer** [comment]
@ZNicoZ I recognized you changed the acceptance criteria. Unfortunately this does not match the customer acceptance criteria anymore. Especially the specification of `sakuli.forwarder.check_mk.url=url` is not appropriate.

**Comment by svettwer** [comment]
> Feedback comNet:
> 
> Parsing der URL kann in CheckMK aktiviert bzw. deaktiviert werden. Default waren sie sich nicht sicher, denken aber, dass per default das Parsing deaktiviert ist.
> 
> Für uns heißt das aus meiner Sicht:
> 
> * Kein WWI spezifisches Feature
> * Konfigurationsschalter, der die Übergabe der URL aktiviert/deaktiviert
> * Konfiguration was / welche URL übergeben wird

@ZNicoZ Why did we not check back with the checkmk documentation/devs instead of asking our customers what they think how it works? Now we've two opinions from two different customers but no real technical specification from the developers.
