### ISSUE TITLE
error states are not updated (prometheus forwarder)

### ISSUE THREAD

**Issue by cliffle** [sakuli/sakuli-enterprise-forwarder#45]
**Short overview**

As a User I want Sakuli to update the error state in the Prometheus forwarder after every test run.

**Detailed error description**

Currently, the error state is not updated when the Sakuli test suite completed successfully. 

After the first error is forwarded, all the following test suites will have an error state even though it was completed successfully.

**Steps to reproduce error**
1. Forward the result of a successful test to the Pushgateway  (`suite_<<test suite name>>_error` is `0`)
2. Forward the result of a failed test to the Pushgateway (`suite_<<test suite name>>_error` is `1`)
3. Forward the result of a successful test to the Pushgateway (`suite_<<test suite name>>_error` is still `1`)

**Comment by svettwer** [comment]
Root cause requried

**Comment by svettwer** [comment]
forwarder does not update gauge in case of successful test.
