### ISSUE TITLE
gearman still validating properties

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli-enterprise-forwarder#65]
Follow up to https://github.com/sakuli/sakuli-enterprise-forwarder/issues/52

See: https://github.com/sakuli/sakuli-enterprise-forwarder/pull/57/files#diff-8098bbb732ae16a3c7767655845222d6R63

Please look around for more unnecessary validation

**Comment by s1hofmann** [comment]
Closed with #62

**Comment by svettwer** [comment]
Awesome! :+1: 
Now that you closed the issue with a reference to #62, I'm pretty sure, we already talked about that a few weeks ago. Good thing that issues are free :joy:
