### ISSUE TITLE
Add node matrix builds again

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli-enterprise-forwarder#93]
We reduced matrix builds on travis as they reduced concurrency for open source projects in the last year. Now that we moved to travis, we should add matrix builds for all active LTS versions of node.

Acceptance criteria

- [x] Sakuli enterprise forwarders are tested on node 12 and 14

**Comment by cliffle** [comment]
Some unit tests for node 10 are failing due to a jsdom bug (https://github.com/jsdom/jsdom/issues/2961). Therefore I'm removing Node 10 from the acceptance criteria
